# Generated by Django 3.0.3 on 2020-02-19 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
